# Generated by Django 4.0.6 on 2022-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('progress', 'Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('ended_time', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ToDolist',
                'verbose_name_plural': 'ToDoLists',
            },
        ),
    ]
