# Generated by Django 4.0.6 on 2022-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
